// demo-ng/src/app/multi/multi.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { RouterExtensions } from 'nativescript-angular';

@Component({
    moduleId: module.id,
    selector: 'ac-multi',
    templateUrl: 'multi.component.html'
})

export class MultiComponent implements OnInit {
    items: any[];
    public selectedIndexes = [0, 2];
    @ViewChild('accordion') accordion: ElementRef;

    constructor(private router: RouterExtensions) {
    }

    expandAll() {
        this.accordion.nativeElement.expandAll();
    }

    collapseAll() {
        this.accordion.nativeElement.collapseAll();
    }

    public headerTemplateSelector = (item: any, index: number, items: any) => {
        return index % 2 === 0 ? 'header-odd' : 'header-even';
    }

    public itemHeaderTemplateSelector = (item: any, index: number, items: any) => {
        return index % 2 === 0 ? 'title-even' : 'title-odd';
    }

    public itemContentTemplateSelector = (item: any, index: number, items: any) => {
        return index % 2 === 0 ? 'content-even' : 'content-odd';
    }

    public footerTemplateSelector = (item: any, index: number, items: any) => {
        return index % 2 === 0 ? 'footer-even' : 'footer-odd';
    }

    goBack() {
        this.router.back();
    }

    ngOnInit(): void {
        this.items = [
            {
                title: '1',
                footer: '10',
                headerText: 'First',
                footerText: '4',
                image: 'http://placehold.it/120x120&text=First',
                children: [
                    {image: '~/images/a9ff17db85f8136619feb0d5a200c0e4.png', text: 'Someone'},
                    {
                        text: 'Help',
                        image: '~/images/svg.jpg'
                    }
                ]
            },
            {
                title: '2',
                footer: '20',
                headerText: 'Second',
                footerText: '5',
                image: 'http://placehold.it/120x120&text=Second',
                children: [{
                    text: 'Me',
                    image: '~/images/shazam.jpg'
                }, {text: 'Stop', image: '~/images/f29.png'}]
            },
            {
                title: '3',
                footer: '30',
                headerText: 'Third',
                footerText: '6',
                image: 'http://placehold.it/120x120&text=Third',
                children: [{text: 'This', image: '~/images/a9ff17db85f8136619feb0d5a200c0e4.png'}, {
                    text: 'Thing',
                    image: '~/images/shazam.jpg'
                }]
            },
            {
                title: '4',
                footer: '40',
                headerText: 'Fourth',
                footerText: '7',
                image: 'http://placehold.it/120x120&text=Fourth',
                children: [{text: 'Now', image: '~/images/batman.png'}, {
                    text: 'Please',
                    image: '~/images/batman.jpg'
                }]
            }
        ];
    }

}
<ActionBar title="Multi Templates">
	<NavigationButton text="Go back" android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
</ActionBar>

<GridLayout columns="*" rows="auto,auto,*">
	<Button row="0" text="Expand All" (tap)="expandAll()"></Button>
	<Button row="1" text="Collapse All" (tap)="collapseAll()"></Button>
	<Accordion #accordion row="2" height="100%" allowMultiple="true" childItems="children" [items]="items"
			   [headerTemplateSelector]="headerTemplateSelector"
			   [itemHeaderTemplateSelector]="itemHeaderTemplateSelector"
			   [itemContentTemplateSelector]="itemContentTemplateSelector"
			   [footerTemplateSelector]="footerTemplateSelector"
	>
		<ng-template let-i="index" let-item="item" acTemplateKey="header-odd">
			<StackLayout>
				<Label height="88" backgroundColor="green" [text]="item.headerText"></Label>
			</StackLayout>
		</ng-template>

		<ng-template let-i="index" let-item="item" acTemplateKey="header-even">
			<StackLayout>
				<Label backgroundColor="orange" [text]="item.headerText"></Label>
			</StackLayout>
		</ng-template>

		<ng-template let-i="index" let-item="item" acTemplateKey="title-odd">
			<StackLayout>
				<Label [text]="item.title"></Label>
			</StackLayout>
		</ng-template>

		<ng-template let-i="index" let-item="item" acTemplateKey="title-even">
			<StackLayout backgroundColor="white">
				<Label [text]="item.title"></Label>
				<Image height="100" width="100" decodeWidth="100" decodeHeight="100" loadMode="async"
					   [src]="item.image"></Image>
			</StackLayout>
		</ng-template>


		<ng-template let-i="index" let-item="item" acTemplateKey="content-odd">
			<StackLayout>
				<Image height="100" decodeWidth="100" decodeHeight="100" loadMode="async" [src]="item.image"></Image>
				<Label height="44" [text]="item.text"></Label>
			</StackLayout>
		</ng-template>

		<ng-template let-i="index" let-item="item" acTemplateKey="content-even">
			<StackLayout>
				<Image height="100" decodeWidth="100" decodeHeight="100" loadMode="async" [src]="item.image"></Image>
				<Label height="10" [text]="item.text"></Label>
			</StackLayout>
		</ng-template>

		<ng-template let-i="index" let-item="item" acTemplateKey="footer-odd">
			<StackLayout>
				<Label backgroundColor="yellow" [text]="item.footerText"></Label>
			</StackLayout>
		</ng-template>

		<ng-template let-i="index" let-item="item" acTemplateKey="footer-even">
			<StackLayout>
				<Label height="44" backgroundColor="blue" [text]="item.footerText"></Label>
			</StackLayout>
		</ng-template>
	</Accordion>
</GridLayout>

// demo-vue/app/components/Multi.vue
<template>
	<Page>
		<ActionBar title="Multi Templates">
			<NavigationButton text="Go back" android.systemIcon="ic_menu_back" @tap="goBack"/>
		</ActionBar>
		<GridLayout columns="*" rows="auto,auto,*">
			<Button row="0" text="Expand All" @tap="expandAll"></Button>
			<Button row="1" text="Collapse All" @tap="collapseAll"></Button>
			<Accordion row="2" height="100%" ref="accordion" allowMultiple="true" childItems="children" for="item of items">
				<v-template if="$odd" name="header-odd">
					<StackLayout>
						<Label backgroundColor="green" :text="item.headerText"></Label>
					</StackLayout>
				</v-template>

				<v-template if="$even" name="header-even">
					<StackLayout>
						<Label backgroundColor="orange" :text="item.headerText"></Label>
					</StackLayout>
				</v-template>

				<v-template if="$odd" name="title-odd">
					<StackLayout backgroundColor="white">
						<Label :text="item.title"></Label>
					</StackLayout>
				</v-template>

				<v-template if="$even" name="title-even">
					<StackLayout backgroundColor="white">
						<Label :text="item.title"></Label>
						<Image height="100" width="100" decodeWidth="400" decodeHeight="400" loadMode="async"
							   :src="item.image"></Image>
					</StackLayout>
				</v-template>


				<v-template if="$odd" name="content-odd">
					<StackLayout>
						<Image decodeWidth="400" decodeHeight="400" loadMode="async" :src="item.image"></Image>
						<Label :text="item.text"></Label>
					</StackLayout>
				</v-template>

				<v-template if="$even" name="content-even">
					<StackLayout>
						<Image decodeWidth="400" decodeHeight="400" loadMode="async" :src="item.image"></Image>
						<Label :text="item.text"></Label>
					</StackLayout>
				</v-template>

				<v-template if="$odd" name="footer-odd">
					<StackLayout>
						<Label backgroundColor="yellow" :text="item.footerText"></Label>
					</StackLayout>
				</v-template>

				<v-template if="$even" name="footer-even">
					<StackLayout>
						<Label backgroundColor="blue" :text="item.footerText"></Label>
					</StackLayout>
				</v-template>
			</Accordion>
		</GridLayout>
	</Page>
</template>

<script>
	export default {
		data() {
			return {
				items: [
					{
						title: '1',
						footer: '10',
						headerText: 'First',
						footerText: '4',
						image: 'http://placehold.it/120x120&text=First',
						children: [
							{ image: '~/assets/images/a9ff17db85f8136619feb0d5a200c0e4.png', text: 'Someone' },
							{
								text: 'Help',
								image: '~/assets/images/svg.jpg'
							}
						]
					},
					{
						title: '2',
						footer: '20',
						headerText: 'Second',
						footerText: '5',
						image: 'http://placehold.it/120x120&text=Second',
						children: [ {
							text: 'Me',
							image: '~/assets/images/shazam.jpg'
						}, { text: 'Stop', image: '~/assets/images/f29.png' } ]
					},
					{
						title: '3',
						footer: '30',
						headerText: 'Third',
						footerText: '6',
						image: 'http://placehold.it/120x120&text=Third',
						children: [ { text: 'This', image: '~/assets/images/a9ff17db85f8136619feb0d5a200c0e4.png' }, {
							text: 'Thing',
							image: '~/assets/images/shazam.jpg'
						} ]
					},
					{
						title: '4',
						footer: '40',
						headerText: 'Fourth',
						footerText: '7',
						image: 'http://placehold.it/120x120&text=Fourth',
						children: [ { text: 'Now', image: '~/assets/images/batman.png' }, {
							text: 'Please',
							image: '~/assets/images/batman.jpg'
						} ]
					}
				]
			}
		},
		methods: {
			goBack: function () {
				this.$navigateBack();
			},
			expandAll: function () {
				this.$refs.accordion.nativeView.expandAll();
			}, collapseAll: function () {
				this.$refs.accordion.nativeView.collapseAll();
			}
		}
	}
</script>

<style scoped>
	ActionBar {
		background-color: #53ba82;
		color: #ffffff;
	}

	.message {
		vertical-align: center;
		text-align: center;
		font-size: 20;
		color: #333333;
	}
</style>
